database:
  host: localhost
  name: mydbname
  username: root
  password: 12345

spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://${database.host}:3306/${database.name}?characterEncoding=utf-8&useUnicode=true&useSSL=false&rewriteBatchedStatements=TRUE

  jpa:
    database: MYSQL
    hibernate.ddl-auto: update
    show-sql: true